- id: center-portal-lambdas-require-elided-password
  name: Center Portal Lambdas require elided password
  description: This hook does what it says on the can
  entry: center-portal-lambdas-elided-password-checker.bash
  pass_filenames: true
  language: script
  types: [text]
- id: center-portal-lambdas-require-nonmocked-db
  name: Center Portal Lambdas require that the db not be mocked for writes
  description: This hook does what it says on the can
  entry: center-portal-lambdas-nonmocked-db-checker.bash
  pass_filenames: true
  language: script
  types: [text]
- id: puc-cloud-require-passing-prettier
  name: Puc Cloud require that files checking in pass prettier
  description: This hook does what it says on the can
  entry: puc-cloud-pretty-checker.bash
  pass_filenames: true
  language: script
  types: [text]
- id: perfectco-conventions
  name: so far, require that the branch name being committed to abides by perfect co branch naming conventions
  description: This hook does what it says on the can
  entry: perfectco-conventions.rb
  pass_filenames: false
  language: ruby
  types: [text]
